language: rust
cache:
    directories:
        - $HOME/sudokusolver/.cargo
        - $HOME/build/fkarg/SudokuSolver/target
before_install:
    - cd sudokusolver
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
 
