language: rust
cache:
    directories:
        - $HOME/.cargo
        - $HOME/.rustup
        - $HOME/build/fkarg/SudokuSolver/sudokusolver/target
before_install:
  - rustup self update
  - rustup update
  - cd sudokusolver
rust:
  - stable
  - beta
matrix:
  fast_finish: true
 
