language: rust
cache:
    directories:
        - $HOME/.cargo
        - $HOME/build/fkarg/SudokuSolver/sudokusolver/target
before_install:
    - cd sudokusolver
rust:
  - stable
  - beta
matrix:
  fast_finish: true
 
